name: Build 25.12.x x86-64
on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "Select the LuCI version"
        required: false
        default: "25.12.1"
        type: choice
        options:
          - 25.12.0
          - 25.12.1
      custom_router_ip:
        description: "Set the router management address (only valid for multi-port routers). Format: 192.168.x.1 or 10.x.x.1"
        required: true
        default: "192.168.100.1"
      profile:
        description: 'Select the package storage size'
        required: true
        type: choice
        default: '1G'
        options:
          - '1G'
          - '2G'
          - '3G'
          - '4G'
      enable_store:
        description: "Include the app store"
        required: false
        type: boolean
        default: false
      include_docker:
        description: |
          Build the Docker plugin?
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "Configure PPPoE credentials?"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "Broadband account (if PPPoE is enabled)"
        required: false
      pppoe_password:
        description: "Broadband password (if PPPoE is enabled)"
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/build25.sh

      - name: Save Custom Router IP into OpenWrt files
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
          echo "The router management address you set is: ${{ github.event.inputs.custom_router_ip }}"
          # A later step maps this file to /etc/config/custom_router_ip.txt on the router so the 99-custom.sh startup script can read the user-defined IP address
      
      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi
      
      - name: Enable Store integration
        run: |
          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/apk-custom-packages.sh
            echo "✅ Added luci-app-store"
          else
            echo "❎ luci-app-store is not enabled"
          fi

      - name: Build ImmortalWrt-x86-64-efi 25.12.x
        run: |
          profile="${{ github.event.inputs.profile }}"
          case "$profile" in
            1G)
              ROOTFS_SIZE=1024
              ;;
            2G)
              ROOTFS_SIZE=2048
              ;;
            3G)
              ROOTFS_SIZE=3072
              ;;
            4G)
              ROOTFS_SIZE=4096
              ;;
          esac
          echo "ROOTFS_SIZE=$ROOTFS_SIZE" >> $GITHUB_ENV
          include_docker="${{ github.event.inputs.include_docker }}"
          luci_version="${{ github.event.inputs.luci_version }}"
          echo "Building for rootfs_size: $profile"
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
            -v "${{ github.workspace }}/x86-64/imm25.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
            -v "${{ github.workspace }}/x86-64/build25.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE=$ROOTFS_SIZE \
            -e INCLUDE_DOCKER=$include_docker \
            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
          immortalwrt/imagebuilder:x86-64-openwrt-${luci_version} /bin/bash /home/build/immortalwrt/build.sh
          

      - name: Create info
        run: |
          cat > ${{ github.workspace }}/router-info.md <<EOF
          ## 📡 Router Administration Information
          <a href="https://wkdaily.cpolar.cn/archives/1">
           <img src="https://img.shields.io/badge/Use-a-mainland-China-mirror-if-downloads-are-slow-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
          </a>
          
          - 🏠 **Administration Address**: ${{ github.event.inputs.custom_router_ip }}
          - 👤 **Username**: root
          - 🔑 **Password**: None
          EOF

          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="#### Docker included by default"
            echo -e "\n$extra_content" >> ${{ github.workspace }}/router-info.md
          else
            echo -e "\n#### Docker not included" >> ${{ github.workspace }}/router-info.md
          fi

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/router-info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
