name: Build 24.10.x RaspBerryPi

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: "Select the router model"
        required: true
        options:
          - rpi-3
          - rpi-4
          - rpi-5
        default: rpi-4
      luci_version:
        description: "Select the LuCI version"
        required: false
        default: "24.10.6"
        type: choice
        options:
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
          - 24.10.5
          - 24.10.6
      enable_store:
        description: "Include the app store"
        required: false
        type: boolean
        default: true
      include_docker:
        description: |
          Build the Docker plugin?
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      size:
        description: 'Enter the firmware build size in MB'
        required: true
        default: '1024'


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/raspberrypi/24.10/build.sh
      
      - name: Enable Store integration
        run: |
          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/custom-packages.sh
            echo "✅ Added luci-app-store"
          else
            echo "❎ luci-app-store is not enabled"
          fi
      
      
      - name: Build raspberrypi ImmortalWrt 24.10.x
        run: |
          luci_version="${{ github.event.inputs.luci_version }}"
          profiles="${{ github.event.inputs.profile }}"
          if [ "$profiles" = "rpi" ]; then
            tag=bcm27xx-bcm2708-openwrt-${luci_version}
            echo "cpu=bcm2708" >> $GITHUB_ENV
          elif [ "$profiles" = "rpi-2" ]; then
            tag=bcm27xx-bcm2709-openwrt-${luci_version}
            echo "cpu=bcm2709" >> $GITHUB_ENV
          elif [ "$profiles" = "rpi-3" ]; then
            ARCH=rpi3.conf
            tag=bcm27xx-bcm2710-openwrt-${luci_version}
            echo "cpu=bcm2710" >> $GITHUB_ENV
          elif [ "$profiles" = "rpi-4" ]; then
            ARCH=rpi4.conf
            tag=bcm27xx-bcm2711-openwrt-${luci_version}
            echo "cpu=bcm2711" >> $GITHUB_ENV
          elif [ "$profiles" = "rpi-5" ]; then
            ARCH=rpi5.conf
            tag=bcm27xx-bcm2712-openwrt-${luci_version}
            echo "cpu=bcm2712" >> $GITHUB_ENV
          fi
          include_docker="${{ github.event.inputs.include_docker }}"
          size="${{ github.event.inputs.size }}"
          
          IFS=',' read -r -a profile_array <<< "$profiles"
          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"
            
            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
              -v "${{ github.workspace }}/files/etc/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
              -v "${{ github.workspace }}/arch/$ARCH:/home/build/immortalwrt/files/etc/opkg/arch.conf" \
              -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
              -v "${{ github.workspace }}/raspberrypi/24.10/build.sh:/home/build/openwrt/build.sh" \
              -e PROFILE=$profile \
              -e LUCI_VERSION=$luci_version \
              -e INCLUDE_DOCKER=$include_docker \
              -e ROOTSIZE=$size \
              immortalwrt/imagebuilder:$tag /bin/bash /home/build/openwrt/build.sh
          done
          ls ${{ github.workspace }}/bin/targets/bcm27xx/${{ env.cpu }}
      
      - name: Create info
        run: |
          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="### Docker included by default"
            echo -e "\n $extra_content" >> ${{ github.workspace }}/info.md
          else
            echo -e "NO docker"
          fi
 
      - name: Upload ImmortalWrt as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: Autobuild-raspberrypi
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/bin/targets/bcm27xx/${{ env.cpu }}/*squashfs-factory.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
